### ISSUE TITLE
fibaroExtra.lua return a error

### ISSUE THREAD

**Issue by julienwetzel** [jangabrielsson/EventRunner#1]
`[18.07.2021] [14:24:00] [ERROR] [QUICKAPP1006]: fibaroExtra.lua:291: attempt to index a function value (global 'table')`

Thanks for your work

**Comment by jangabrielsson** [comment]
This is my first comment on Github(!) . Seems to be the table.unpack that causes the issue? You haven accidentally refined the table function?

**Comment by julienwetzel** [comment]
\o/ Yeah ^^
I do not remember in which command this error appeared. I think with a self: trace (). In my text, there were 3 variables, one of which had a nil value. That's why I got this message.

**Comment by jangabrielsson** [comment]
You mean the tracef function from fibaroExtra?
Yes, in general it's a very common problem, also when doing string.format and you have more %-directives than arguments.
Anyway, I pushed v0.915 that protects all the fibaro.debugf and QuickApp:debugf etc with a pcall and error that points to the calling source line instead of into fibaroExtra.lua.
A general principle for fibaroExtra is that it should be helpful with error messages - if you find something else let me know.

**Comment by julienwetzel** [comment]
No, I did not use ftrace in this case.
Yes ok, if I get a message from fibaroExtra that does not point to the source line, I will let you know :)
Thank you
